name: Sync Upstream and Deploy

on:
  # 支持手动触发
  workflow_dispatch:
  # 监听上游仓库的 webhook 事件
  repository_dispatch:
    types: [upstream_update]
  # 保持定时同步作为备份方案
  schedule:
    - cron: '0 */8 * * *'  # 每8小时检查一次

jobs:
  sync_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Configure Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      
      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/jaywcjlove/reference.git
          git remote -v
      
      - name: Sync with upstream
        run: |
          git fetch upstream gh-pages
          git merge upstream/gh-pages --no-edit || {
            echo "Merge conflict occurred. Aborting merge..."
            git merge --abort
            exit 1
          }
          git push origin gh-pages
        
      - name: Trigger Cloudflare Pages deployment
        if: success()
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/pages/webhooks/deploy_hooks/a0c0031e-f2b4-4507-a6cf-1f714bcb4992"
      
      - name: Notify on failure
        if: failure()
        run: |
          echo "Sync or deployment failed. Please check the workflow logs."
