name: Sync Upstream and Deploy

on:
  schedule:
    - cron: '0 */8 * * *'  # 每8小时检查一次
  workflow_dispatch:
  repository_dispatch:
    types: [upstream_update]

jobs:
  sync_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Configure Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      
      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/jaywcjlove/reference.git
          git fetch upstream gh-pages
      
      - name: Check for updates
        id: check
        run: |
          UPSTREAM_SHA=$(git rev-parse upstream/gh-pages)
          CURRENT_SHA=$(git rev-parse HEAD)
          if [ "$UPSTREAM_SHA" != "$CURRENT_SHA" ]; then
            echo "UPDATE_NEEDED=true" >> $GITHUB_ENV
          else
            echo "UPDATE_NEEDED=false" >> $GITHUB_ENV
          fi
      
      - name: Sync with upstream
        if: env.UPDATE_NEEDED == 'true'
        run: |
          git merge upstream/gh-pages --no-edit || {
            echo "Merge conflict occurred. Aborting merge..."
            git merge --abort
            exit 1
          }
          git push origin gh-pages
        
      - name: Trigger Cloudflare Pages deployment
        if: env.UPDATE_NEEDED == 'true'
        run: |
          RESPONSE=$(curl -X POST "https://api.cloudflare.com/client/v4/pages/webhooks/deploy_hooks/a0c0031e-f2b4-4507-a6cf-1f714bcb4992")
          echo "Deployment triggered. Response: $RESPONSE"

      - name: Print sync status
        run: |
          if [ "${{ env.UPDATE_NEEDED }}" == "true" ]; then
            echo "Updates were found and synchronized"
          else
            echo "Repository is already up to date with upstream"
          fi
